# Generated by Django 2.1.5 on 2019-02-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('mięsne', 'mięsne'), ('wegańskie', 'wegańskie'), ('wegetariańskie', 'wegetariańskie'), ('dietetyczne', 'dietetyczne'), ('pikantne', 'pikantne'), ('orientalne', 'orientalne'), ('dla dzieci', 'dla dzieci')], max_length=20),
        ),
    ]
